/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AltAddLiquidity {
        "title": string;
    }
}
declare global {
    interface HTMLAltAddLiquidityElement extends Components.AltAddLiquidity, HTMLStencilElement {
    }
    var HTMLAltAddLiquidityElement: {
        prototype: HTMLAltAddLiquidityElement;
        new (): HTMLAltAddLiquidityElement;
    };
    interface HTMLElementTagNameMap {
        "alt-add-liquidity": HTMLAltAddLiquidityElement;
    }
}
declare namespace LocalJSX {
    interface AltAddLiquidity {
        "title"?: string;
    }
    interface IntrinsicElements {
        "alt-add-liquidity": AltAddLiquidity;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "alt-add-liquidity": LocalJSX.AltAddLiquidity & JSXBase.HTMLAttributes<HTMLAltAddLiquidityElement>;
        }
    }
}
