.PHONY: \
	build usage \

usage:
	@echo "usage: make <command> [OPTIONS]"
	@echo
	@echo "Available options:"
	@echo
	@echo "Available commands:"
	@echo "  build               -- Run spago build"

build:
	spago build