export const FETCH_LOGIN_START = 'FETCH_LOGIN_START';
export const FETCH_LOGIN_SUCCESS = 'FETCH_LOGIN_SUCCESS';
export const FETCH_LOGIN_FAILED = 'FETCH_LOGIN_FAILED';
export const LOGOUT = 'LOGOUT';

export const FETCH_GAMES_START = 'FETCH_GAMES_START';
export const FETCH_GAMES_SUCCESS = 'FETCH_GAMES_SUCCESS';
export const FETCH_GAMES_FAILED = 'FETCH_GAMES_FAILED';

export const FETCH_GAME_START = 'FETCH_GAME_START';
export const FETCH_GAME_SUCCESS = 'FETCH_GAME_SUCCESS';
export const FETCH_GAME_FAILED = 'FETCH_GAME_FAILED';

export const FETCH_GAME_CONTRACT_START = 'FETCH_GAME_CONTRACT_START';
export const FETCH_GAME_CONTRACT_SUCCESS = 'FETCH_GAME_CONTRACT_SUCCESS';
export const FETCH_GAME_CONTRACT_FAILED = 'FETCH_GAME_CONTRACT_FAILED';

export const FETCH_GAME_BETS_START = 'FETCH_GAME_BETS_START';
export const FETCH_GAME_BETS_SUCCESS = 'FETCH_GAME_BETS_SUCCESS';
export const FETCH_GAME_BETS_FAILED = 'FETCH_GAME_BETS_FAILED';

export const FETCH_MAKE_BET_START = 'FETCH_MAKE_BET_START';
export const FETCH_MAKE_BET_SUCCESS = 'FETCH_MAKE_BET_SUCCESS';
export const FETCH_MAKE_BET_FAILED = 'FETCH_MAKE_BET_FAILED';