export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';

export const FETCH_GAMES_START = 'FETCH_GAMES_START';
export const FETCH_GAMES_SUCCESS = 'FETCH_GAMES_SUCCESS';
export const FETCH_GAMES_FAILED = 'FETCH_GAMES_FAILED';

export const FETCH_GAME_START = 'FETCH_GAME_START';
export const FETCH_GAME_SUCCESS = 'FETCH_GAME_SUCCESS';
export const FETCH_GAME_FAILED = 'FETCH_GAME_FAILED';

export const FETCH_GAME_CONTRACT_START = 'FETCH_GAME_CONTRACT_START';
export const FETCH_GAME_CONTRACT_SUCCESS = 'FETCH_GAME_CONTRACT_SUCCESS';
export const FETCH_GAME_CONTRACT_FAILED = 'FETCH_GAME_CONTRACT_FAILED';

export const FETCH_GAME_BETS_START = 'FETCH_GAME_BETS_START';
export const FETCH_GAME_BETS_SUCCESS = 'FETCH_GAME_BETS_SUCCESS';
export const FETCH_GAME_BETS_FAILED = 'FETCH_GAME_BETS_FAILED';