export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';

export const FETCH_MY_TOKENS_START = 'FETCH_MY_TOKENS_START';
export const FETCH_MY_TOKENS_SUCCESS = 'FETCH_MY_TOKENS_SUCCESS';
export const FETCH_MY_TOKENS_FAILED = 'FETCH_MY_TOKENS_FAILED';

export const FETCH_ADD_TOKEN_START = 'FETCH_ADD_TOKEN_START';
export const FETCH_ADD_TOKEN_SUCCESS = 'FETCH_ADD_TOKEN_SUCCESS';
export const FETCH_ADD_TOKEN_FAILED = 'FETCH_ADD_TOKEN_FAILED';