export const LOGOUT = 'LOGOUT';
export const FETCH_LOGIN_START = 'FETCH_LOGIN_START';
export const FETCH_LOGIN_SUCCESS = 'FETCH_LOGIN_SUCCESS';
export const FETCH_LOGIN_FAILED = 'FETCH_LOGIN_FAILED';

export const FETCH_MY_TOKENS_START = 'FETCH_MY_TOKENS_START';
export const FETCH_MY_TOKENS_SUCCESS = 'FETCH_MY_TOKENS_SUCCESS';
export const FETCH_MY_TOKENS_FAILED = 'FETCH_MY_TOKENS_FAILED';

export const FETCH_STOREFRONT_START = 'FETCH_STOREFRONT_START';
export const FETCH_STOREFRONT_SUCCESS = 'FETCH_STOREFRONT_SUCCESS';
export const FETCH_STOREFRONT_FAILED = 'FETCH_STOREFRONT_FAILED';

export const FETCH_ADD_TOKEN_START = 'FETCH_ADD_TOKEN_START';
export const FETCH_ADD_TOKEN_SUCCESS = 'FETCH_ADD_TOKEN_SUCCESS';
export const FETCH_ADD_TOKEN_FAILED = 'FETCH_ADD_TOKEN_FAILED';

export const FETCH_SELL_TOKEN_START = 'FETCH_SELL_TOKEN_START';
export const FETCH_SELL_TOKEN_SUCCESS = 'FETCH_SELL_TOKEN_SUCCESS';
export const FETCH_SELL_TOKEN_FAILED = 'FETCH_SELL_TOKEN_FAILED';

export const FETCH_BUY_TOKEN_START = 'FETCH_BUY_TOKEN_START';
export const FETCH_BUY_TOKEN_SUCCESS = 'FETCH_BUY_TOKEN_SUCCESS';
export const FETCH_BUY_TOKEN_FAILED = 'FETCH_BUY_TOKEN_FAILED';

export const FETCH_CANCEL_SELL_TOKEN_START = 'FETCH_CANCEL_SELL_TOKEN_START';
export const FETCH_CANCEL_SELL_TOKEN_SUCCESS = 'FETCH_CANCEL_SELL_TOKEN_SUCCESS';
export const FETCH_CANCEL_SELL_TOKEN_FAILED = 'FETCH_CANCEL_SELL_TOKEN_FAILED';