/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AltSwap {
        "title": string;
    }
}
declare global {
    interface HTMLAltSwapElement extends Components.AltSwap, HTMLStencilElement {
    }
    var HTMLAltSwapElement: {
        prototype: HTMLAltSwapElement;
        new (): HTMLAltSwapElement;
    };
    interface HTMLElementTagNameMap {
        "alt-swap": HTMLAltSwapElement;
    }
}
declare namespace LocalJSX {
    interface AltSwap {
        "title"?: string;
    }
    interface IntrinsicElements {
        "alt-swap": AltSwap;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "alt-swap": LocalJSX.AltSwap & JSXBase.HTMLAttributes<HTMLAltSwapElement>;
        }
    }
}
